spring:
   profiles: aws_rds
   application:
     name: point_of_sale_app
   main:
     allow-bean-definition-overriding: true
   sql.init.mode: always
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://sql6.freesqldatabase.com:3306/sql6679474
     username: sql6679474
     password: hbV9nAtZAU
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       format_sql: true
       show_sql: true
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.db.datajson.upload: true
# Discovery Server Access
eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 45
    metadata-map:
      server.servlet.context-path: ${server.servlet.context-path}
  client:
    enabled: true
    serviceUrl:
       defaultZone: http://localhost:1111/eureka/
# HTTP Server (Tomcat) Port
server: 
  port: 2222
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true
---
spring:
   profiles:  
     active: local
   application:
     name: posapp
   main:
     allow-bean-definition-overriding: true
   sql.init.mode: always
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/point_of_sale_app
     username: root
     password: root
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       format_sql: true
       show_sql: true
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.db.datajson.upload: true
# Discovery Server Access
eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress : false
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    enabled: true
    serviceUrl:
       defaultZone: http://localhost:1111/eureka/
# HTTP Server (Tomcat) Port
server: 
  port: 2222
  servlet: 
   context-path: '/'
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true
---
spring:
   profiles: dev
   application:
     name: point_of_sale_app
   main:
     allow-bean-definition-overriding: true
   sql.init.mode: always
   datasource:
     driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
     url: jdbc:sqlserver://pointofsale.database.windows.net:1433;database=point_of_sale_app;user=ramkishor05@pointofsale;password=Ram@9450;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
     username: ramkishor05
     password: Ram@9450
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       format_sql: true
       show_sql: true
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/
# HTTP Server (Tomcat) Port
server: 
  port: 2222
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true

